# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
platform :ios do
  lane :develop do
    # USYM_TOKEN（例: Unity Cloud Diagnosticsなど）を設定（今回はダミー）
    sh("export USYM_UPLOAD_AUTH_TOKEN=dummy")

    # Xcodeのコード署名設定を手動に変更
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "../ProjectPath/Unity-iPhone.xcodeproj",
      team_id: "XXXXXXXXXX", # チームID
      targets: ["Unity-iPhone", "UnityFramework"],
      code_sign_identity: "Apple Distribution"
    )

    # Provisioning Profile の割り当て
    update_project_provisioning(
      xcodeproj: "../ProjectPath/Unity-iPhone.xcodeproj",
      target_filter: "Unity-iPhone",
      profile: "/path/to/ProvisioningProfiles/YourApp.mobileprovision", # Provisioning Profileのパス
      code_signing_identity: "Apple Distribution"
    )

    # IPAのビルド処理
    build_app(
      scheme: "Unity-iPhone",
      project: "../ProjectPath/Unity-iPhone.xcodeproj",
      output_directory: "../Builds",
      output_name: "YourApp.ipa",
      export_method: "app-store",
      include_bitcode: false,
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        compileBitcode: false,
        uploadBitcode: false,
        provisioningProfiles: {
          "com.example.yourapp" => "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" # Provisioning Profileの名前とUUID
        },
        signingCertificate: "Apple Distribution",
        signingStyle: "manual",
        stripSwiftSymbols: true,
        teamID: "XXXXXXXXXX"
      },
      include_symbols: false,
      xcargs: "IDEBuildOperationMaxNumberOfConcurrentCompileTasks=8 GCC_GENERATE_DEBUGGING_SYMBOLS=NO DEBUG_INFORMATION_FORMAT=dwarf ONLY_ACTIVE_ARCH=YES VALID_ARCHS=arm64"
    )
  end
end
